This is my first supervised machine learning model that works on credit card fraud data set.

In [33]:

import pandas as pd

# Loading data sets with pandas.
Credit_Fraud_Train = 'C:/Users/Jeremy/Downloads/archive/train.csv'
Credit_Fraud_Test = 'C:/Users/Jeremy/Downloads/archive/test.csv'

train_data = pd.read_csv(Credit_Fraud_Train)
test_data = pd.read_csv(Credit_Fraud_Test)

# Describes the columns the data has.
train_data.columns
test_data.columns

Index(['Unnamed: 0', 'trans_date_trans_time', 'cc_num', 'merchant', 'category',
       'amt', 'first', 'last', 'gender', 'street', 'city', 'state', 'zip',
       'lat', 'long', 'city_pop', 'job', 'dob', 'trans_num', 'unix_time',
       'merch_lat', 'merch_long', 'is_fraud'],
      dtype='str')

Getting an idea on what I am working with.

In [34]:
train_data.describe()
train_data.describe()

,Unnamed: 0,cc_num,amt,zip,lat,long,city_pop,unix_time,merch_lat,merch_long,is_fraud
count,1.296675e+06,1.296675e+06,1.296675e+06,1.296675e+06,1.296675e+06,1.296675e+06,1.296675e+06,1.296675e+06,1.296675e+06,1.296675e+06,1.296675e+06
mean,6.483370e+05,4.171920e+17,7.035104e+01,4.880067e+04,3.853762e+01,-9.022634e+01,8.882444e+04,1.349244e+09,3.853734e+01,-9.022646e+01,5.788652e-03
std,3.743180e+05,1.308806e+18,1.603160e+02,2.689322e+04,5.075808e+00,1.375908e+01,3.019564e+05,1.284128e+07,5.109788e+00,1.377109e+01,7.586269e-02
min,0.000000e+00,6.041621e+10,1.000000e+00,1.257000e+03,2.002710e+01,-1.656723e+02,2.300000e+01,1.325376e+09,1.902779e+01,-1.666712e+02,0.000000e+00
25%,3.241685e+05,1.800429e+14,9.650000e+00,2.623700e+04,3.462050e+01,-9.679800e+01,7.430000e+02,1.338751e+09,3.473357e+01,-9.689728e+01,0.000000e+00
50%,6.483370e+05,3.521417e+15,4.752000e+01,4.817400e+04,3.935430e+01,-8.747690e+01,2.456000e+03,1.349250e+09,3.936568e+01,-8.743839e+01,0.000000e+00
75%,9.725055e+05,4.642255e+15,8.314000e+01,7.204200e+04,4.194040e+01,-8.015800e+01,2.032800e+04,1.359385e+09,4.195716e+01,-8.023680e+01,0.000000e+00
max,1.296674e+06,4.992346e+18,2.894890e+04,9.978300e+04,6.669330e+01,-6.795030e+01,2.906700e+06,1.371817e+09,6.751027e+01,-6.695090e+01,1.000000e+00

Setting up the input features, selecting target predictions, and getting rid of null values.

In [35]:
train_data = train_data.dropna(axis=0)
test_data = test_data.dropna(axis=0)

train_features = ['cc_num', 'amt', 'zip', 'unix_time', 'lat', 'long', 'merch_lat', 'merch_long']

y = train_data.is_fraud

X = train_data[train_features]

X.head()

,cc_num,amt,zip,unix_time,lat,long,merch_lat,merch_long
0,2703186189652095,4.97,28654,1325376018,36.0788,-81.1781,36.011293,-82.048315
1,630423337322,107.23,99160,1325376044,48.8878,-118.2105,49.159047,-118.186462
2,38859492057661,220.11,83252,1325376051,42.1808,-112.2620,43.150704,-112.154481
3,3534093764340240,45.00,59632,1325376076,46.2306,-112.1138,47.034331,-112.561071
4,375534208663984,41.96,24433,1325376186,38.4207,-79.4629,38.674999,-78.632459

Building the Machine Learning model using the scikit-learn library.

In [36]:
from sklearn.model_selection import train_test_split

train_X, val_X, train_y, val_y = train_test_split(X, y, random_state = 0)

CCFraud_model = DecisionTreeRegressor()

CCFraud_model.fit(train_X, train_y)

val_predictions = CCFraud_model.predict(val_X)

print("Making predictions on the following people:")

print(X)

print("The predictions are:")

print(val_predictions)

Making predictions on the following people:
                      cc_num     amt    zip   unix_time      lat      long  \
0           2703186189652095    4.97  28654  1325376018  36.0788  -81.1781
1               630423337322  107.23  99160  1325376044  48.8878 -118.2105
2             38859492057661  220.11  83252  1325376051  42.1808 -112.2620
3           3534093764340240   45.00  59632  1325376076  46.2306 -112.1138
4            375534208663984   41.96  24433  1325376186  38.4207  -79.4629
...                      ...     ...    ...         ...      ...       ...
1296670       30263540414123   15.56  84735  1371816728  37.7175 -112.4777
1296671     6011149206456997   51.70  21790  1371816739  39.2667  -77.5101
1296672     3514865930894695  105.93  88325  1371816752  32.9396 -105.8189
1296673     2720012583106919   74.90  57756  1371816816  43.3526 -102.5411
1296674  4292902571056973207    4.30  59871  1371816817  45.8433 -113.8748

         merch_lat  merch_long
0        36.011293  -82.048315
1        49.159047 -118.186462
2        43.150704 -112.154481
3        47.034331 -112.561071
4        38.674999  -78.632459
...            ...         ...
1296670  36.841266 -111.690765
1296671  38.906881  -78.246528
1296672  33.619513 -105.130529
1296673  42.788940 -103.241160
1296674  46.565983 -114.186110

[1296675 rows x 8 columns]
The predictions are:
[0. 0. 0. ... 0. 0. 0.]

Time to evaluate my model.

In [37]:
from sklearn.metrics import mean_absolute_error

print("The means absolute error is:")

print(mean_absolute_error(val_y, val_predictions))

The means absolute error is:
0.007039538018749479

Fine tuning my model to get better performance.

In [38]:
from sklearn.metrics import mean_absolute_error
from sklearn.tree import DecisionTreeRegressor

def get_mae(max_leaf_nodes, train_X, val_X, train_y, val_y):
    CCFraud_model2 = DecisionTreeRegressor(max_leaf_nodes=max_leaf_nodes, random_state=0)
    CCFraud_model2.fit(train_X, train_y)
    pred_val = CCFraud_model2.predict(val_X)
    mae = mean_absolute_error(val_y, pred_val)
    return(mae)

# Comparing MAE with differing values of max leaf nodes
for max_leaf_nodes in [5, 50, 500, 5000]:
    my_mae = get_mae(max_leaf_nodes, train_X, val_X, train_y, val_y)
    print("Max leaf nodes: %d  \t\t Mean Absolute Error: %d" %(max_leaf_nodes, my_mae))

Max leaf nodes: 5  		 Mean Absolute Error: 0
Max leaf nodes: 50  		 Mean Absolute Error: 0
Max leaf nodes: 500  		 Mean Absolute Error: 0
Max leaf nodes: 5000  		 Mean Absolute Error: 0